name: Build pyodide static site

on:
  workflow_dispatch:

jobs:
  # Build job
  build:
    # <Not provided for brevity>
    # At a minimum this job should upload artifacts using actions/upload-pages-artifact
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        python-version: ["3.11"]

    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Clone git repos
      run: |
        git clone -b webview --single-branch https://github.com/bumps/bumps
        git clone -b webview --single-branch https://github.com/reflectometry/refl1d
    - name: Build bumps
      run: |
        cd bumps
        python setup.py bdist_wheel
        echo "BUMPS_PYTHON_WHL=$(ls dist)" >> $GITHUB_ENV
    - name: Build refl1d
      run: |
        cd refl1d
        BUILD_EXTENSION=True python setup.py bdist_wheel
        echo "REFL1D_PYTHON_WHL=$(ls dist)" >> $GITHUB_ENV
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: initialize bumps client
      run: |
        npm i
        npm link
      working-directory: bumps/bumps/webview/client
    - name: initialize refl1d client
      run: |
        npm i
        npm link bumps-webview-client
      working-directory: refl1d/refl1d/webview/client
    - name: build client
      working-directory: refl1d/refl1d/webview/client
      run: |
        rm -rf dist
        npm run build_standalone
        DIST_SUBDIR=$(ls dist)
        echo "DIST_SUBDIR=$DIST_SUBDIR" >> $GITHUB_ENV
        mkdir dist/$DIST_SUBDIR/assets/wheels
        cp ../../../../bumps/dist/*.whl dist/$DIST_SUBDIR/assets/wheels/
        cp ../../../../refl1d/dist/*.whl dist/$DIST_SUBDIR/assets/wheels/
      env:
         CI: ""
    
    - name: Upload pages artifact client artifact
      uses: actions/upload-pages-artifact@v1.0.7
      with:
        path: refl1d/refl1d/webview/client/dist/$DIST_SUBDIR

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
