# This is a basic workflow to help you get started with Actions

name: Build-Embedded

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-warn-script-location wheel numpy==1.19.3 scipy matplotlib wxpython periodictable nose
        pip install git+https://github.com/bumps/bumps.git
        python setup.py bdist_wheel
        
    - name: Run a script
      run: |
        .\extra\build_win_installer.ps1
        cd ..
        mv dist\Refl1D*.zip dist\Refl1D_latest.zip
      shell: powershell
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Refl1D_latest.zip
        path: dist\Refl1D_latest.zip
    - name: Update release
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release: unstable
        tag: sid
        files: dist\Refl1D_latest.zip
     
